### ISSUE TITLE
Legal Issues

### ISSUE THREAD

**Issue by Foggalong** [yassern/unixporn-bot#1]
Hey, u/Foggalong from Reddit and mod of r/unixporn here. Not gonna lie, there are all sorts of vague problems with this being an opt-out system and I'd recommend you close that account or otherwise make drastic changes to the way that it works.

1. Lots of users might be uncomfortable with their content being on Instagram. Last I heard, agreeing to the service agreement basically meant signing ownership of the content (including for commercial use) over to Instagram. [Reddit has similarly shitty clauses](https://redd.it/3uz0s1) but different people trust different websites.
2. It's not quite the same as having a Twitter account which just links to posts from the sub, it's quite literally rehosting the content on an entirely separate platform with separate TOS which the users of this sub probably won't be aware of. This alone puts you in a legally grey area.
3. When a user posts content to Reddit they retain copyright ownership, and are only explicitly giving Reddit the company permission to redistribute, create derivative works, etc. This permission does not extend to users of Reddit, so that means that to legally take their work and share it elsewhere you need to ask each user explicit permission beforehand (rather than allowing people to opt-out).
4. To get around points 2 & 3 you'd have to get us (the moderators) to include a subreddit rule saying that by posting you were granting us permission to reshare the content on other (proprietary) platforms. Even if I was up for this, which I'm not, it would be a legally grey solution to the problem since I don't think subreddit rules can officially override the Reddit TOS.

So yeah, probably don't do this or otherwise switch it to an opt-in system only. I'm happy to talk about this with you more (either here [or on Reddit](https://www.reddit.com/r/unixporn/comments/78tokb/unixporn_on_instagram/doy00vf/)), but thought you should probably be aware of this before the project gained too much traction or you poured too much time into it.

**Comment by yassern** [comment]
wow, are you from numix project? i am your fan.
the account is already deleted.
I'm a follower of the https://twitter.com/runixporn and it did inspire me to apply the same idea with new technologies that i learned.
I think ricing as art so i want let the content more accessible, reddit is not very well known in my country;
it is a pity the complexity of this situation but i learned so much with this little project, thank you to all community and sorry for taking your time.

**Comment by Foggalong** [comment]
Hey, yeah I am! Thanks :)

Thanks for the quick action on this! No need to apologise for taking my time, I'm sorry that it had to happen. Glad that it was still a useful learning experience in making the project though
